- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: Course
    prompt: please enter the course name
    private: false # not confidentials
  - name: Trainer 
    prompt: please enter the trainer name
    private: false # not confidentials
  - name: Duration
    prompt: please enter the duration
    private: false # not confidentials
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi iam learning {{Course}}, Duration is: {{Duration}}, Trainer: {{Trainer}}"  