- name: variables to print
  hosts: web
  vars:
    Course: "Devops with AWS"
    Duration: "120HRs"
    Trainer: "siva kumar reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug: 
      msg: "Hi iam learing: {{Course}}, Duration is: {{Duration}}, Trainer is: {{Trainer}}"