- name: nginx server install and run
  hosts: web
  become: yes # sudo access
  tasks: 
  - name: instl nginx server
    ansible.builtin.package: #hetrogenius module that can work for all distributions
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    